openapi: 3.0.0
info:
  title: Pricing API
  description: REST API for product pricing queries
  version: '1.0.0'
servers:
  - url: 'http://localhost:8080'
paths:
  /api/v1/prices:
    get:
      operationId: getApplicablePrice
      summary: Get applicable price for a product
      description: Returns the applicable price for a product based on application date, product ID, and brand ID
      parameters:
        - name: applicationDate
          in: query
          required: true
          description: Application date in ISO 8601 format (e.g., 2020-06-14T10:00:00)
          schema:
            type: string
            format: date-time
        - name: productId
          in: query
          required: true
          description: Product identifier
          schema:
            type: integer
            format: int64
        - name: brandId
          in: query
          required: true
          description: Brand identifier (1 = ZARA)
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Applicable price found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceResponse'
        '404':
          description: No applicable price found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    PriceResponse:
      type: object
      required:
        - productId
        - brandId
        - priceList
        - startDate
        - endDate
        - price
      properties:
        productId:
          type: integer
          format: int64
          description: Product identifier
          example: 35455
        brandId:
          type: integer
          format: int64
          description: Brand identifier
          example: 1
        priceList:
          type: integer
          description: Applicable price list identifier
          example: 1
        startDate:
          type: string
          format: date-time
          description: Start date of the price application period
          example: "2020-06-14T00:00:00"
        endDate:
          type: string
          format: date-time
          description: End date of the price application period
          example: "2020-12-31T23:59:59"
        price:
          type: number
          format: double
          description: Final price to apply
          example: 35.50
        currency:
          type: string
          description: ISO currency code
          example: "EUR"

    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        status:
          type: integer
        error:
          type: string
        message:
          type: string
        path:
          type: string